Typo: usage → print_usage

diff --git a/byob b/byob
--- a/byob
+++ b/byob
@@ -20,7 +20,7 @@ while getopts :I: option
 do
   case "$option" in
     I) ocaml_lib_dirs="$ocaml_lib_dirs $OPTARG" ;;
-    *) echo "Invalid option"; usage; exit 1 ;;
+    *) echo "Invalid option"; print_usage; exit 1 ;;
   esac
 done
 
